apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: myapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: api
        image: nefor32/myapp:1e945732dea1c1e803a916c758a8bfac3237bf5d
        imagePullPolicy: Never
        ports:
        - containerPort: 4200