apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: myapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: api
        image: nefor32/myapp:56891a9f6ed8eb3fe2e66bd317d9b7b2808da976
        ports:
        - containerPort: 4200